config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  root to: redirect("/cats")

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  # after_initialize :ensure_session_token

  attr_reader :password

  has_many :cats, dependent: :destroy
  has_many :cat_rental_requests, dependent: :destroy

  has_many :tokens


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_not_signed_in!, only: [:new]
  
  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to cats_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign up</h1>

<form  action="<%= users_url %>" method="post">
  <input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">
  <label for="username">Username: </label>
  <input type="text" name="user[username]" value="">

  <label for="username">Password: </label>
  <input type="password" name="user[password]" value="">

  <%= button_to("Create User", users_url) %>
</form>